services:
  authlog-monitor:
    image: auth-log-monitor
    container_name: authlog-monitor
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      # - LOG_TYPE=${LOG_TYPE}
    networks:
      - authlog-net
    volumes:
      - ./scripts:/tmp/scripts
      - /var/log/auth.log:/var/log/auth.log:ro 
    restart: always

networks:
  authlog-net:
    name: authlog-net
