services:
  authlog-monitor:
    image: thechef3179/auth-log-monitor:latest
    container_name: authlog-monitor
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - SLEEP_TIME=${SLEEP_TIME}
    networks:
      - authlog-net
    volumes:
      - /var/log/auth.log:/var/log/auth.log:ro 
    restart: unless-stopped

networks:
  authlog-net:
    name: authlog-net
